version: '3.8'

x-common-variables: &common-variables
  TZ: UTC
  LOG_LEVEL: INFO

x-restart-policy: &restart-policy
  restart: unless-stopped

x-cpu-limits: &cpu-limits
  cpus: '2.0'
  cpu_shares: 1024

x-memory-limits: &memory-limits
  mem_limit: 2g
  memswap_limit: 2g

x-resource-limits: &resource-limits
  cpus: '2.0'
  cpu_shares: 1024
  mem_limit: 2g
  memswap_limit: 2g
  deploy:
    resources:
      limits:
        cpus: '2.0'
        memory: 2G
      reservations:
        cpus: '0.5'
        memory: 512M

networks:
  trading-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  timescaledb_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local
  pgadmin_data:
    driver: local
  sniper_bot_data:
    driver: local
  # Redis data volume removed - using DragonflyDB Cloud instead

services:
  # TimescaleDB for time-series market data and trade history
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: trading-bot-timescaledb
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
      <<: *common-variables
      POSTGRES_DB: ${TIMESCALEDB_DBNAME:-trading_db}
      POSTGRES_USER: ${TIMESCALEDB_USER:-trading_user}
      POSTGRES_PASSWORD: ${TIMESCALEDB_PASSWORD:-trading_password}
      # For production, avoid trusting host auth; use POSTGRES_HOST_AUTH_METHOD only for dev/testing
      POSTGRES_HOST_AUTH_METHOD: ${TIMESCALEDB_HOST_AUTH_METHOD:-}
    ports:
      # External port can be configured via TIMESCALEDB_PORT environment variable
      # Internal container port remains 5432 for container-to-container communication
      # Example: Set TIMESCALEDB_PORT=5433 in .env to avoid port conflicts
      - "${TIMESCALEDB_PORT:-5432}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      # TimescaleDB initialization handled by extension installation on first run
    networks:
      trading-network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALEDB_USER:-trading_user} -d ${TIMESCALEDB_DBNAME:-trading_db}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: trading-bot-prometheus
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus_rules:/etc/prometheus/rules:ro
    networks:
      trading-network:
        ipv4_address: 172.20.0.12
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Grafana for visualization dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: trading-bot-grafana
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      <<: *common-variables
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-trading_admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SECURITY_COOKIE_SECURE: "false"
      GF_SECURITY_COOKIE_SAMESITE: lax
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_ORG_ROLE: Editor
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # Provisioning & dashboards are bind-mounted from repo for easier editing
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      trading-network:
        ipv4_address: 172.20.0.13
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # AlertManager for alert routing
  alertmanager:
    image: prom/alertmanager:latest
    container_name: trading-bot-alertmanager
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    networks:
      trading-network:
        ipv4_address: 172.20.0.14
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DragonflyDB for high-performance caching and Pub/Sub message bus
  # Production DragonflyDB Cloud connection via REDIS_URL environment variable
  # No local Redis service needed - DragonflyDB provides Redis-compatible API

  # Rust Data Consumer for Geyser
  data-consumer:
    build:
      context: .
      dockerfile: rust-modules/Dockerfile.data-consumer
    container_name: trading-bot-data-consumer
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    environment:
      <<: *common-variables
      RUST_LOG: info
      GEYSER_ENDPOINT: ${GEYSER_ENDPOINT}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "9191:9191" # Metrics port
    networks:
      trading-network:
        ipv4_address: 172.20.0.18
    # DragonflyDB Cloud connection - no local dependency needed

  # pgAdmin for TimescaleDB management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trading-bot-pgadmin
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    environment:
      <<: *common-variables
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@trading-bot.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pgadmin_password}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"  # pgAdmin web interface
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      # pgAdmin server configuration can be added manually via UI
    networks:
      trading-network:
        ipv4_address: 172.20.0.16
    depends_on:
      timescaledb:
        condition: service_healthy

  # Trading Bot Application
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: trading-bot-app
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    env_file:
      - .env
      - .env.docker
    environment:
      <<: *common-variables
      # Environment
      TRADING_ENV: ${TRADING_ENV:-development}

      # Database connections
      TIMESCALEDB_URL: postgresql://${TIMESCALEDB_USER:-trading_user}:${TIMESCALEDB_PASSWORD:-trading_password}@timescaledb:5432/${TIMESCALEDB_DBNAME:-trading_db}
      REDIS_URL: ${REDIS_URL}
      ENABLE_RUST_CONSUMER: "true"

      # API Keys (loaded from .env file)
      HELIUS_API_KEY: ${HELIUS_API_KEY}
      QUICKNODE_RPC_URL: ${QUICKNODE_RPC_URL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}

      # Wallet configuration
      WALLET_ADDRESS: ${WALLET_ADDRESS}
      WALLET_PRIVATE_KEY_PATH: /app/secrets/wallet.keypair

      # Trading parameters
      INITIAL_CAPITAL: ${INITIAL_CAPITAL:-1.0}
      EXECUTION_MODE: ${EXECUTION_MODE:-paper}
      MAX_POSITION_SIZE: ${MAX_POSITION_SIZE:-0.10}
      MAX_DRAWDOWN: ${MAX_DRAWDOWN:-0.15}

      # Multi-Token Arbitrage (2025 Enhanced)
      ARBITRAGE_ENABLED: ${ARBITRAGE_ENABLED:-true}
      MAX_CONCURRENT_ARBITRAGE: ${MAX_CONCURRENT_ARBITRAGE:-3}
      MIN_PROFIT_THRESHOLD: ${MIN_PROFIT_THRESHOLD:-5.0}
      RUST_FFI_ENABLED: ${RUST_FFI_ENABLED:-true}
      ARBITRAGE_TRIANGULAR_ENABLED: ${ARBITRAGE_TRIANGULAR_ENABLED:-true}
      ARBITRAGE_CROSS_DEX_ENABLED: ${ARBITRAGE_CROSS_DEX_ENABLED:-true}
      ARBITRAGE_FLASH_LOAN_ENABLED: ${ARBITRAGE_FLASH_LOAN_ENABLED:-false}
      ARBITRAGE_EXECUTION_ENABLED: ${ARBITRAGE_EXECUTION_ENABLED:-true}
      ARBITRAGE_CRITICAL_PRIORITY: ${ARBITRAGE_CRITICAL_PRIORITY:-true}
      ARBITRAGE_MULTI_LEG_ENABLED: ${ARBITRAGE_MULTI_LEG_ENABLED:-true}
      ARBITRAGE_TIMEOUT_SECONDS: ${ARBITRAGE_TIMEOUT_SECONDS:-30}
      ARBITRAGE_RETRY_ATTEMPTS: ${ARBITRAGE_RETRY_ATTEMPTS:-2}

      # PumpFun Integration
      PUMPPORTAL_API_KEY: ${PUMPPORTAL_API_KEY}
      HONEYPOT_API_KEY: ${HONEYPOT_API_KEY}

      # Jito Bundle Execution
      JITO_MAINNET_URL: ${JITO_MAINNET_URL:-https://mainnet.block-engine.jito.wtf}
      JITO_AMSTERDAM_URL: ${JITO_AMSTERDAM_URL:-https://amsterdam.block-engine.jito.wtf}
      JITO_AUTH_KEY: ${JITO_AUTH_KEY}

      # Monitoring
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FORMAT: json

      # Development flags
      MOCK_APIS: ${MOCK_APIS:-false}
      VERBOSE_LOGGING: ${VERBOSE_LOGGING:-false}
    ports:
      - "8082:8082"  # Health check port (includes /metrics endpoint)
    volumes:
      - ./src:/app/src:ro
      - ./config:/app/config:ro
      - ./secrets:/app/secrets:ro
      - ./logs:/app/logs
      - ./rust-modules:/app/rust-modules:ro
    networks:
      trading-network:
        ipv4_address: 172.20.0.20
    depends_on:
      timescaledb:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    # DragonflyDB Cloud connection - no local dependency needed
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: trading-bot-node-exporter
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      trading-network:
        ipv4_address: 172.20.0.30

  # cAdvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: trading-bot-cadvisor
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    command:
      - '--housekeeping_interval=30s'
      - '--docker_only=true'
    ports:
      - "8083:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      trading-network:
        ipv4_address: 172.20.0.31

  # =============================================================================
  # PumpFun Sniper Bot for Backtesting
  # =============================================================================
  sniper-bot:
    build:
      context: .
      dockerfile: rust-modules/Dockerfile.sniper-bot
      target: ${BUILD_TARGET:-production}
    container_name: trading-bot-sniper
    <<: *restart-policy
    <<: *resource-limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env
      - .env.docker
    environment:
      <<: *common-variables
      # Environment
      TRADING_ENV: ${TRADING_ENV:-development}
      BOT_MODE: ${BOT_MODE:-backtest}

      # Database connections
      TIMESCALEDB_URL: postgresql://${TIMESCALEDB_USER:-trading_user}:${TIMESCALEDB_PASSWORD:-trading_password}@timescaledb:5432/${TIMESCALEDB_DBNAME:-trading_db}
      REDIS_URL: ${REDIS_URL}

      # API Keys (loaded from .env file)
      HELIUS_API_KEY: ${HELIUS_API_KEY}
      QUICKNODE_RPC_URL: ${QUICKNODE_RPC_URL}
      PUMPPORTAL_API_KEY: ${PUMPPORTAL_API_KEY}
      HONEYPOT_API_KEY: ${HONEYPOT_API_KEY}

      # Wallet configuration (sniper-specific)
      SNIPER_WALLET_PRIVATE_KEY: ${SNIPER_WALLET_PRIVATE_KEY}
      SNIPER_WALLET_ADDRESS: ${SNIPER_WALLET_ADDRESS:-${WALLET_ADDRESS}}

      # Sniper configuration
      INITIAL_CAPITAL: ${SNIPER_INITIAL_CAPITAL:-1.0}
      MAX_POSITION_SIZE: ${SNIPER_MAX_POSITION_SIZE:-0.05}
      TP_THRESHOLD: ${TP_THRESHOLD:-1.5}
      SL_THRESHOLD: ${SL_THRESHOLD:-0.8}
      MIN_LP_BURN_RATE: ${MIN_LP_BURN_RATE:-90.0}
      MIN_SOCIAL_MENTIONS: ${MIN_SOCIAL_MENTIONS:-10}
      HONEYPOT_CHECK_ENABLED: ${HONEYPOT_CHECK_ENABLED:-true}

      # Backtest configuration
      BACKTEST_MODE: ${BACKTEST_MODE:-true}
      BACKTEST_START_DATE: ${BACKTEST_START_DATE:-2024-01-01}
      BACKTEST_END_DATE: ${BACKTEST_END_DATE:-2024-12-31}
      BACKTEST_INITIAL_CAPITAL: ${BACKTEST_INITIAL_CAPITAL:-10.0}
      BACKTEST_DATA_SOURCE: ${BACKTEST_DATA_SOURCE:-historical}

      # RPC 2025 Features
      ENABLE_SHREDSTREAM: ${HELIUS_ENABLE_SHREDSTREAM:-false}
      ENABLE_LIL_JIT: ${QUICKNODE_LIL_JIT_ENABLED:-false}
      PREFERRED_RPC_PROVIDER: ${RPC_PREFERRED_PROVIDER:-auto}
      DYNAMIC_PRIORITY_FEES: ${PRIORITY_FEE_ESTIMATION_ENABLED:-true}

      # Monitoring
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FORMAT: json
      METRICS_ENABLED: true

      # Performance
      MAX_CONCURRENT_TRADES: ${MAX_CONCURRENT_SNIPER_TRADES:-3}
      TRADE_EXECUTION_TIMEOUT_MS: ${SNIPER_TRADE_TIMEOUT_MS:-5000}
      POSITION_MONITORING_INTERVAL_MS: ${POSITION_MONITORING_INTERVAL_MS:-1000}

      # Risk management
      MAX_DAILY_TRADES: ${MAX_DAILY_TRADES:-50}
      MAX_OPEN_POSITIONS: ${MAX_OPEN_POSITIONS:-5}
      MIN_TRADE_INTERVAL_SECONDS: ${MIN_TRADE_INTERVAL_SECONDS:-30}

    ports:
      - "8084:8080"  # Sniper bot API and metrics
      - "8085:8081"  # Sniper bot WebSocket for real-time updates

    volumes:
      - ./rust-modules/sniper-bot:/app:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data:ro
      - ./secrets:/app/secrets:ro
      - sniper_bot_data:/app/data/sniper

    networks:
      trading-network:
        ipv4_address: 172.20.0.40

    depends_on:
      timescaledb:
        condition: service_healthy
      prometheus:
        condition: service_healthy

    # DragonflyDB Cloud connection - no local dependency needed

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

    # Sniper bot specific labels for monitoring
    labels:
      - "trading-bot.service=sniper-bot"
      - "trading-bot.type=backtest"
      - "trading-bot.monitoring=prometheus"
      - "trading-bot.logs=grafana"

