[package]
name = "mojo-trading-bot"
version = "0.1.0"
edition = "2021"
description = "High-performance algorithmic trading bot for Solana memecoins"
authors = ["MojoRust Team"]
license = "MIT"

[lib]
name = "mojo_trading_bot"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies (minimal versions to avoid conflicts)
ed25519-dalek = "2.0"
sha2 = "0.10"
hmac = "0.12"
aes-gcm = "0.10"
rand = "0.8"
zeroize = "1.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Async and networking
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }

# Secrets management
infisical = { version = "0.2", features = ["async"] }
async-trait = "0.1"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# Encoding
bs58 = "0.5"
hex = "0.4"
base64 = "0.21"

# Math and statistics
num-bigint = "0.4"
num-traits = "0.2"
ordered-float = "3.9"

# FFI
libc = "0.2"

# Additional dependencies
regex = "1.10"
constant_time_eq = "0.2"
pbkdf2 = "0.12"
env_logger = "0.10"
vergen = { version = "8.2", features = ["build", "git", "gitcl"] }
lazy_static = "1.4"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
mockall = "0.12"

[features]
default = ["std"]
std = []
no-std = []