[package]
name = "mojo-trading-bot"
version = "0.1.0"
edition = "2021"
description = "High-performance algorithmic trading bot for Solana memecoins"
authors = ["MojoRust Team"]
license = "MIT"

[lib]
name = "mojo_trading_bot"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Solana dependencies
solana-sdk = "1.18"
solana-client = "1.18"
solana-account-decoder = "1.18"
solana-transaction-status = "1.18"
solana-program = "1.18"
anchor-client = "0.30"
anchor-lang = "0.30"

# Cryptography
ed25519-dalek = "2.0"
sha2 = "0.10"
hmac = "0.12"
aes-gcm = "0.10"
rand = "0.8"
zeroize = "1.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
borsh = "0.10"

# Async and networking
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-tungstenite = "0.20"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# Math and statistics
num-bigint = "0.4"
num-traits = "0.2"
ordered-float = "3.9"

# FFI
libffi = "3.2"
libc = "0.2"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"

[features]
default = ["std"]
std = []
no-std = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
debug = true