# AlertManager configuration for MojoRust Trading Bot
# Routes alerts from Prometheus to Telegram and other notification channels

global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'trading-bot-alerts@example.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Custom message templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  receiver: 'telegram'
  group_by: ['alertname', 'severity', 'component']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  # Routes for different alert severities
  routes:

    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'telegram-critical'
      group_wait: 10s
      repeat_interval: 1h

    # Trading alerts - specialized routing
    - match:
        component: trading
      receiver: 'telegram-trading'
      group_interval: 2m

    # System alerts
    - match:
        component: system
      receiver: 'telegram-system'

    # Risk alerts
    - match:
        component: risk
      receiver: 'telegram-critical'
      group_wait: 5s
      repeat_interval: 30m

    # API alerts
    - match:
        component: api
      receiver: 'telegram-api'

# Notification receivers
receivers:

  # Default Telegram receiver
  - name: 'telegram'
    webhook_configs:
      - url: 'http://trading-bot:8082/api/alerts/telegram'
        send_resolved: true
        http_config:
          bearer_token: '${TELEGRAM_WEBHOOK_TOKEN}'

  # Critical alerts Telegram receiver
  - name: 'telegram-critical'
    webhook_configs:
      - url: 'http://trading-bot:8082/api/alerts/telegram/critical'
        send_resolved: true
        http_config:
          bearer_token: '${TELEGRAM_WEBHOOK_TOKEN}'

  # Trading alerts Telegram receiver
  - name: 'telegram-trading'
    webhook_configs:
      - url: 'http://trading-bot:8082/api/alerts/telegram/trading'
        send_resolved: true
        http_config:
          bearer_token: '${TELEGRAM_WEBHOOK_TOKEN}'

  # System alerts Telegram receiver
  - name: 'telegram-system'
    webhook_configs:
      - url: 'http://trading-bot:8082/api/alerts/telegram/system'
        send_resolved: true
        http_config:
          bearer_token: '${TELEGRAM_WEBHOOK_TOKEN}'

  # API alerts Telegram receiver
  - name: 'telegram-api'
    webhook_configs:
      - url: 'http://trading-bot:8082/api/alerts/telegram/api'
        send_resolved: true
        http_config:
          bearer_token: '${TELEGRAM_WEBHOOK_TOKEN}'

  # Email receiver (optional)
  - name: 'email'
    email_configs:
      - to: '${ALERT_EMAIL}'
        from: 'trading-bot-alerts@example.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${SMTP_USERNAME}'
        auth_password: '${SMTP_PASSWORD}'
        require_tls: true
        headers:
          Subject: '[Trading Bot Alert] {{ .GroupLabels.alertname }}'

  # Slack receiver (optional)
  - name: 'slack'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#trading-alerts'
        title: '{{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

# Inhibit rules to suppress less important alerts when critical ones are firing
inhibit_rules:

  # Inhibit warning alerts when critical alerts are firing for same component
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['component', 'alertname']

  # Inhibit non-trading alerts when trading critical alerts fire
  - source_match:
      severity: critical
      component: trading
    target_match:
      severity: warning
    equal: ['component']

# Time intervals for routing
time_intervals:
  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']

  - name: 'after-hours'
    time_intervals:
      - times:
          - start_time: '17:00'
            end_time: '09:00'
        weekdays: ['monday:friday']
      - weekdays: ['saturday', 'sunday']