# Prometheus configuration for MojoRust Trading Bot
# Scrape configuration for trading bot metrics and system monitoring

global:
  scrape_interval: 15s        # By default, scrape targets every 15 seconds
  evaluation_interval: 15s   # Evaluate rules every 15 seconds
  external_labels:
    environment: "production"
    service: "trading-bot"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alert rules
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:

  # Trading Bot Application Metrics
  - job_name: 'trading-bot'
    static_configs:
      - targets: ['trading-bot:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s      # More frequent for trading metrics
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-bot-1'
    metric_relabel_configs:
      # Keep trading_bot, http, health, readiness, and arbitrage metrics
      - source_labels: [__name__]
        regex: 'trading_bot_.*|http_.*|health_.*|readiness_.*|arbitrage_.*'
        action: keep

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-server'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-server'
      - source_labels: [name]
        regex: 'trading-bot.*'
        target_label: container
        replacement: 'trading-bot'

  # TimescaleDB PostgreSQL Exporter (if enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'timescaledb'

  # Redis Exporter (if enabled)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # Grafana metrics (optional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    basic_auth:
      username: admin
      password: trading_admin
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'grafana'

  # AlertManager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'alertmanager'

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal.compression: true