# Trading-specific alert rules for MojoRust Trading Bot
# Monitors trading performance, execution, and risk metrics

groups:
  - name: trading_performance
    rules:

      # High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(trading_bot_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          component: trading
        annotations:
          summary: "High error rate detected in trading bot"
          description: "Trading bot error rate is {{ $value | humanizePercentage }} (threshold: 10%)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/high-error-rate"

      # High API Latency Alert
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(trading_bot_api_latency_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High API latency detected"
          description: "API latency p95 is {{ $value }}s (threshold: 0.5s)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/high-latency"

      # Circuit Breaker Triggered Alert
      - alert: CircuitBreakerTriggered
        expr: trading_bot_circuit_breaker_open == 1
        for: 1m
        labels:
          severity: critical
          component: risk
        annotations:
          summary: "Circuit breaker triggered"
          description: "Circuit breaker {{ $labels.breaker }} is open - trading halted"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/circuit-breaker"

      # Low Portfolio Balance Alert
      - alert: LowBalance
        expr: trading_bot_portfolio_balance_sol < 0.1
        for: 5m
        labels:
          severity: warning
          component: portfolio
        annotations:
          summary: "Low portfolio balance"
          description: "Portfolio balance is {{ $value }} SOL (threshold: 0.1 SOL)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/low-balance"

      # High Drawdown Alert
      - alert: HighDrawdown
        expr: trading_bot_current_drawdown > 0.15
        for: 2m
        labels:
          severity: critical
          component: risk
        annotations:
          summary: "High drawdown detected"
          description: "Current drawdown is {{ $value | humanizePercentage }} (threshold: 15%)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/high-drawdown"

      # Low Win Rate Alert
      - alert: LowWinRate
        expr: trading_bot_win_rate < 0.4 and trading_bot_total_trades > 20
        for: 30m
        labels:
          severity: warning
          component: performance
        annotations:
          summary: "Low win rate detected"
          description: "Win rate is {{ $value | humanizePercentage }} after {{ $labels.total_trades }} trades"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/low-win-rate"

      # Consecutive Losses Alert
      - alert: ConsecutiveLosses
        expr: trading_bot_consecutive_losses >= 5
        for: 1m
        labels:
          severity: warning
          component: risk
        annotations:
          summary: "Consecutive losses detected"
          description: "{{ $value }} consecutive losses detected"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/consecutive-losses"

      # High Slippage Alert
      - alert: HighSlippage
        expr: trading_bot_avg_slippage > 0.03
        for: 10m
        labels:
          severity: warning
          component: execution
        annotations:
          summary: "High slippage detected"
          description: "Average slippage is {{ $value | humanizePercentage }} (threshold: 3%)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/high-slippage"

      # No Trading Activity Alert
      - alert: NoTradingActivity
        expr: time() - trading_bot_last_trade_timestamp > 3600 and trading_bot_monitoring_active == 1
        for: 5m
        labels:
          severity: warning
          component: trading
        annotations:
          summary: "No trading activity detected"
          description: "No trades executed in the last hour despite monitoring being active"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/no-trading-activity"

      # High Execution Time Alert
      - alert: HighExecutionTime
        expr: trading_bot_avg_execution_time > 2.0
        for: 5m
        labels:
          severity: warning
          component: execution
        annotations:
          summary: "High execution time detected"
          description: "Average execution time is {{ $value }}s (threshold: 2s)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/high-execution-time"

      # Risk Limit Breach Alert
      - alert: RiskLimitBreach
        expr: trading_bot_risk_limit_utilization > 0.9
        for: 1m
        labels:
          severity: critical
          component: risk
        annotations:
          summary: "Risk limit breach detected"
          description: "Risk limit utilization is {{ $value | humanizePercentage }} (threshold: 90%)"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/risk-limit-breach"

      # Position Size Alert
      - alert: LargePositionSize
        expr: trading_bot_max_position_size > trading_bot_portfolio_value_sol * 0.3
        for: 1m
        labels:
          severity: warning
          component: risk
        annotations:
          summary: "Large position size detected"
          description: "Maximum position size ({{ $value }} SOL) exceeds 30% of portfolio value"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/large-position-size"

      # Strategy Performance Alert
      - alert: PoorStrategyPerformance
        expr: trading_bot_strategy_win_rate < 0.35 and trading_bot_strategy_total_trades > 10
        for: 1h
        labels:
          severity: warning
          component: performance
        annotations:
          summary: "Poor strategy performance"
          description: "Strategy {{ $labels.strategy }} win rate is {{ $value | humanizePercentage }} after {{ $labels.total_trades }} trades"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/poor-strategy-performance"

      # API Rate Limit Alert
      - alert: APIRateLimit
        expr: trading_bot_rate_limit_hits_total > 0
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "API rate limit reached"
          description: "Rate limit hit for {{ $labels.api }} on endpoint {{ $labels.endpoint }}"
          runbook_url: "https://github.com/your-org/mojorust/docs/alerts/api-rate-limit"