groups:
  - name: mojorust_trading_alerts
    rules:
      # Critical Trading Alerts
      - alert: TradingSuccessRateLow
        expr: trading_success_rate < 80
        for: 2m
        labels:
          severity: critical
          service: mojorust
          component: trading
        annotations:
          summary: "Trading success rate is critically low"
          description: "Trading success rate is {{ $value }}% for the last 2 minutes, which is below the 80% threshold."

      - alert: HighTransactionFailureRate
        expr: rate(trading_failed_transactions[5m]) / rate(trading_total_transactions[5m]) > 0.3
        for: 1m
        labels:
          severity: critical
          service: mojorust
          component: trading
        annotations:
          summary: "High transaction failure rate detected"
          description: "Transaction failure rate is {{ $value | humanizePercentage }} for the last 5 minutes."

      - alert: NegativeProfitTrend
        expr: rate(trading_profit_per_second_lamports[10m]) < -1000
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: trading
        annotations:
          summary: "Negative profit trend detected"
          description: "Profit rate is {{ $value }} lamports/second for the last 10 minutes."

      - alert: TransactionQueueBacklog
        expr: trading_transaction_queue_depth > 50
        for: 3m
        labels:
          severity: warning
          service: mojorust
          component: trading
        annotations:
          summary: "Transaction queue backlog detected"
          description: "Transaction queue depth is {{ $value }} transactions."

      # Arbitrage Alerts
      - alert: LowArbitrageSuccessRate
        expr: arbitrage_success_rate < 70
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: arbitrage
        annotations:
          summary: "Arbitrage success rate is low"
          description: "Arbitrage success rate is {{ $value }}% for the last 5 minutes."

      - alert: HighArbitrageSlippage
        expr: histogram_quantile(0.95, rate(arbitrage_slippage_percentage_bucket[5m])) > 3.0
        for: 2m
        labels:
          severity: warning
          service: mojorust
          component: arbitrage
        annotations:
          summary: "High arbitrage slippage detected"
          description: "95th percentile slippage is {{ $value }}% for the last 5 minutes."

      - alert: NoArbitrageOpportunities
        expr: increase(arbitrage_opportunities_detected_total[10m]) == 0
        for: 15m
        labels:
          severity: warning
          service: mojorust
          component: arbitrage
        annotations:
          summary: "No arbitrage opportunities detected"
          description: "No arbitrage opportunities have been detected in the last 15 minutes."

      # Flash Loan Alerts
      - alert: FlashLoanSuccessRateLow
        expr: flash_loan_success_rate < 75
        for: 3m
        labels:
          severity: critical
          service: mojorust
          component: flash_loan
        annotations:
          summary: "Flash loan success rate is critically low"
          description: "Flash loan success rate is {{ $value }}% for the last 3 minutes."

      - alert: FlashLoanExecutionTimeout
        expr: histogram_quantile(0.95, rate(flash_loan_execution_time_seconds_bucket[5m])) > 60
        for: 2m
        labels:
          severity: warning
          service: mojorust
          component: flash_loan
        annotations:
          summary: "Flash loan execution timeouts detected"
          description: "95th percentile flash loan execution time is {{ $value }} seconds."

      - alert: FlashLoanProviderUnhealthy
        expr: flash_loan_provider_health < 0.8
        for: 1m
        labels:
          severity: warning
          service: mojorust
          component: flash_loan
        annotations:
          summary: "Flash loan provider health is degraded"
          description: "Flash loan provider health is {{ $value | humanizePercentage }}."

      # RPC Router Alerts
      - alert: RPCSuccessRateLow
        expr: rpc_success_rate < 90
        for: 2m
        labels:
          severity: critical
          service: mojorust
          component: rpc_router
        annotations:
          summary: "RPC success rate is critically low"
          description: "RPC success rate is {{ $value }}% for the last 2 minutes."

      - alert: HighRPCLatency
        expr: histogram_quantile(0.95, rate(rpc_request_duration_seconds_bucket[5m])) > 1.0
        for: 2m
        labels:
          severity: warning
          service: mojorust
          component: rpc_router
        annotations:
          summary: "High RPC latency detected"
          description: "95th percentile RPC latency is {{ $value }} seconds."

      - alert: NoActiveRPCConnections
        expr: rpc_active_connections == 0
        for: 30s
        labels:
          severity: critical
          service: mojorust
          component: rpc_router
        annotations:
          summary: "No active RPC connections"
          description: "All RPC connections are down."

      # Data Pipeline Alerts
      - alert: DataPipelineStalled
        expr: rate(data_events_processed_total[2m]) < 10
        for: 3m
        labels:
          severity: critical
          service: mojorust
          component: data_pipeline
        annotations:
          summary: "Data pipeline appears stalled"
          description: "Event processing rate is {{ $value }} events/second for the last 2 minutes."

      - alert: HighRedisLag
        expr: data_redis_lag_seconds > 5
        for: 1m
        labels:
          severity: warning
          service: mojorust
          component: data_pipeline
        annotations:
          summary: "High Redis message lag detected"
          description: "Redis message lag is {{ $value }} seconds."

      - alert: LowFilterEfficiency
        expr: data_filter_efficiency < 90
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: data_pipeline
        annotations:
          summary: "Low filter efficiency detected"
          description: "Filter efficiency is {{ $value }}% for the last 5 minutes."

      # System Performance Alerts
      - alert: HighMemoryUsage
        expr: system_memory_usage_bytes / (1024 * 1024 * 1024) > 8
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}GB."

      - alert: HighCPUUsage
        expr: system_cpu_usage_percentage > 80
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}%."

      - alert: TooManyOpenFiles
        expr: system_open_files > 1000
        for: 5m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High number of open files"
          description: "Open file count is {{ $value }}."

      # Performance Alerts
      - alert: HighEndToEndLatency
        expr: histogram_quantile(0.95, rate(performance_end_to_end_latency_seconds_bucket[5m])) > 10
        for: 2m
        labels:
          severity: warning
          service: mojorust
          component: performance
        annotations:
          summary: "High end-to-end latency detected"
          description: "95th percentile end-to-end latency is {{ $value }} seconds."

      - alert: LowThroughput
        expr: performance_throughput_transactions_per_second < 0.1
        for: 10m
        labels:
          severity: warning
          service: mojorust
          component: performance
        annotations:
          summary: "Low trading throughput detected"
          description: "Trading throughput is {{ $value }} transactions/second."

      # Risk Management Alerts
      - alert: HighDrawdown
        expr: risk_drawdown_percentage > 15
        for: 1m
        labels:
          severity: critical
          service: mojorust
          component: risk
        annotations:
          summary: "High portfolio drawdown detected"
          description: "Portfolio drawdown is {{ $value }}%."

      - alert: CircuitBreakerTripped
        expr: increase(risk_circuit_breaker_trips_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          service: mojorust
          component: risk
        annotations:
          summary: "Circuit breaker has been tripped"
          description: "Circuit breaker was tripped {{ $value }} times in the last 5 minutes."

      - alert: StopLossActivated
        expr: increase(risk_stop_loss_activations_total[1m]) > 0
        for: 0s
        labels:
          severity: warning
          service: mojorust
          component: risk
        annotations:
          summary: "Stop loss has been activated"
          description: "Stop loss was activated {{ $value }} times in the last minute."

      # Error and Retry Alerts
      - alert: HighErrorRate
        expr: error_rate > 10
        for: 2m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% for the last 2 minutes."

      - alert: HighTimeoutRate
        expr: rate(timeout_count_total[5m]) / rate(error_count_total[5m]) > 0.5
        for: 3m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High timeout rate detected"
          description: "Timeout rate is {{ $value | humanizePercentage }} of all errors for the last 5 minutes."

      - alert: HighRetryRate
        expr: rate(retry_count_total[5m]) / rate(trading_total_transactions[5m]) > 0.2
        for: 3m
        labels:
          severity: warning
          service: mojorust
          component: system
        annotations:
          summary: "High retry rate detected"
          description: "Retry rate is {{ $value | humanizePercentage }} for the last 5 minutes."